"""helpdesk_mvp_initial

Revision ID: 3f83e61dc228
Revises: 
Create Date: 2026-08-20 19:49:58.800446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f83e61dc228'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_id'), 'customer', ['id'], unique=False)
    op.create_table('knowledge_base_category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_knowledge_base_category_id'), 'knowledge_base_category', ['id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_table('service_level_agreement_policy',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_level_agreement_policy_id'), 'service_level_agreement_policy', ['id'], unique=False)
    op.create_table('ticket_priority',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_ticket_priority_id'), 'ticket_priority', ['id'], unique=False)
    op.create_table('two_factor',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_two_factor_expires_at'), 'two_factor', ['expires_at'], unique=False)
    op.create_table('service_level_agreement_priority_target',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=False),
    sa.Column('priority_id', sa.Uuid(), nullable=False),
    sa.Column('first_response_minutes', sa.Integer(), nullable=False),
    sa.Column('resolution_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['service_level_agreement_policy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['priority_id'], ['ticket_priority.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_level_agreement_priority_target_id'), 'service_level_agreement_priority_target', ['id'], unique=False)
    op.create_index(op.f('ix_service_level_agreement_priority_target_policy_id'), 'service_level_agreement_priority_target', ['policy_id'], unique=False)
    op.create_index(op.f('ix_service_level_agreement_priority_target_priority_id'), 'service_level_agreement_priority_target', ['priority_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('avatar_key', sa.String(length=500), nullable=True),
    sa.Column('locale', sa.String(length=10), server_default='pt-BR', nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='SET DEFAULT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('customer_member',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_member_customer_id'), 'customer_member', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_member_id'), 'customer_member', ['id'], unique=False)
    op.create_index(op.f('ix_customer_member_user_id'), 'customer_member', ['user_id'], unique=False)
    op.create_table('knowledge_base_article',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['category_id'], ['knowledge_base_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_knowledge_base_article_author_id'), 'knowledge_base_article', ['author_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_article_category_id'), 'knowledge_base_article', ['category_id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_article_id'), 'knowledge_base_article', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_base_article_status'), 'knowledge_base_article', ['status'], unique=False)
    op.create_table('session',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('client_ip', sa.String(length=200), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('requester_user_id', sa.Uuid(), nullable=False),
    sa.Column('assignee_user_id', sa.Uuid(), nullable=True),
    sa.Column('service_level_agreement_policy_id', sa.Uuid(), nullable=True),
    sa.Column('response_due_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_due_at', sa.DateTime(), nullable=True),
    sa.Column('first_responded_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('service_level_agreement_status', sa.String(length=50), nullable=True),
    sa.Column('hold_started_at', sa.DateTime(), nullable=True),
    sa.Column('total_hold_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignee_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['priority_id'], ['ticket_priority.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_level_agreement_policy_id'], ['service_level_agreement_policy.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_assignee_user_id'), 'ticket', ['assignee_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_customer_id'), 'ticket', ['customer_id'], unique=False)
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_number'), 'ticket', ['number'], unique=True)
    op.create_index('ix_ticket_priority_id_fk', 'ticket', ['priority_id'], unique=False)
    op.create_index(op.f('ix_ticket_requester_user_id'), 'ticket', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_service_level_agreement_policy_id'), 'ticket', ['service_level_agreement_policy_id'], unique=False)
    op.create_index(op.f('ix_ticket_status'), 'ticket', ['status'], unique=False)
    op.create_table('user_notification',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'notification_id')
    )
    op.create_table('ticket_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['user.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_message_author_user_id'), 'ticket_message', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_ticket_message_id'), 'ticket_message', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_message_ticket_id'), 'ticket_message', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_message_ticket_id'), table_name='ticket_message')
    op.drop_index(op.f('ix_ticket_message_id'), table_name='ticket_message')
    op.drop_index(op.f('ix_ticket_message_author_user_id'), table_name='ticket_message')
    op.drop_table('ticket_message')
    op.drop_table('user_notification')
    op.drop_index(op.f('ix_ticket_status'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_service_level_agreement_policy_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_requester_user_id'), table_name='ticket')
    op.drop_index('ix_ticket_priority_id_fk', table_name='ticket')
    op.drop_index(op.f('ix_ticket_number'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_customer_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_assignee_user_id'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_table('session')
    op.drop_index(op.f('ix_knowledge_base_article_status'), table_name='knowledge_base_article')
    op.drop_index(op.f('ix_knowledge_base_article_id'), table_name='knowledge_base_article')
    op.drop_index(op.f('ix_knowledge_base_article_category_id'), table_name='knowledge_base_article')
    op.drop_index(op.f('ix_knowledge_base_article_author_id'), table_name='knowledge_base_article')
    op.drop_table('knowledge_base_article')
    op.drop_index(op.f('ix_customer_member_user_id'), table_name='customer_member')
    op.drop_index(op.f('ix_customer_member_id'), table_name='customer_member')
    op.drop_index(op.f('ix_customer_member_customer_id'), table_name='customer_member')
    op.drop_table('customer_member')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_service_level_agreement_priority_target_priority_id'), table_name='service_level_agreement_priority_target')
    op.drop_index(op.f('ix_service_level_agreement_priority_target_policy_id'), table_name='service_level_agreement_priority_target')
    op.drop_index(op.f('ix_service_level_agreement_priority_target_id'), table_name='service_level_agreement_priority_target')
    op.drop_table('service_level_agreement_priority_target')
    op.drop_index(op.f('ix_two_factor_expires_at'), table_name='two_factor')
    op.drop_table('two_factor')
    op.drop_index(op.f('ix_ticket_priority_id'), table_name='ticket_priority')
    op.drop_table('ticket_priority')
    op.drop_index(op.f('ix_service_level_agreement_policy_id'), table_name='service_level_agreement_policy')
    op.drop_table('service_level_agreement_policy')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_knowledge_base_category_id'), table_name='knowledge_base_category')
    op.drop_table('knowledge_base_category')
    op.drop_index(op.f('ix_customer_id'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
