server {
    listen 80;
    server_name localhost;

    root /code/app/assets;

    location / {
        proxy_pass http://fastapi:8000;  # Uvicorn is running on localhost:8000
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_cache_bypass $http_upgrade;

        # To handle large uploads, adjust client_max_body_size if needed
        client_max_body_size 100M;
    }

    # Optionally, you can also serve static files from Nginx if you have any
    location /static/ {
        alias /code/app/assets/;
        expires 30d;
    }
}